apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: api
spec:
  type: ClusterIP  # Utiliser NodePort ou LoadBalancer selon les besoins
  ports:
    - port: 80             # Port sur lequel le service sera exposé
      targetPort: 8000     # Port du conteneur où l'application écoute
      protocol: TCP
  selector:
    app: api
