name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  # Optionally, trigger on tags for versioned releases
  # tags:
  #   - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Extract repository and image information
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=raw,value=latest

      # 5. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Specify the build context and Dockerfile location
          context: ./ticketing_api
          file: ./ticketing_api/Dockerfile
          
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optionally, set build arguments or cache settings here
          # build-args: |
          #   ENV=production
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      # 6. Optional: Display the pushed image name
      - name: Print Image Info
        run: echo "Image pushed to ${{ steps.meta.outputs.tags }}"
